name: Extract ZIP

on:
  workflow_dispatch: # Menjalankan secara manual

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Unzip
      run: sudo apt-get install -y unzip

    - name: Extract ZIP File
      run: unzip src/assets/session.zip -d session/
