name: Extract ZIP

on:
  workflow_dispatch: # Menjalankan secara manual

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch master
      uses: actions/checkout@v3
      with:
        ref: master  # Checkout ke branch master

    - name: Install Unzip
      run: sudo apt-get install -y unzip

    - name: Extract session.zip
      run: unzip crazyyyyBvvvv-yessssyelll/src/session.zip
